/**
 * Robustly extracts a JSON object from a model response. Accepts pure JSON,
 * fenced ```json blocks, JSON embedded in surrounding text, reasoning/think tags,
 * and repairs common LLM JSON syntax artifacts (trailing commas, unescaped newlines, etc).
 */
export function extractJsonObject(text: string): unknown {
  const cleaned = stripReasoningTags(text).trim();
  if (!cleaned) {
    throw new Error("Model response did not contain valid JSON (empty response after stripping reasoning)");
  }

  // 1. Quick try on the entire cleaned text
  const direct = tryParse(cleaned);
  if (isObject(direct)) return direct;

  // 2. Extract and try all fenced markdown code blocks
  const fences = extractFencedBlocks(cleaned);
  // Try fences in reverse order (models often write sample schemas first and final payloads last)
  for (let i = fences.length - 1; i >= 0; i--) {
    const parsed = tryParse(fences[i]);
    if (isObject(parsed)) return parsed;
  }

  // 3. Scan for balanced JSON object candidates in the text
  const candidates = findJsonCandidates(cleaned);
  for (const candidate of candidates) {
    const parsed = tryParse(candidate);
    if (isObject(parsed)) return parsed;
  }

  // 4. If all else fails, try extracting from raw text before reasoning stripping as a fallback
  if (cleaned !== text.trim()) {
    const rawCandidates = findJsonCandidates(text.trim());
    for (const candidate of rawCandidates) {
      const parsed = tryParse(candidate);
      if (isObject(parsed)) return parsed;
    }
  }

  throw new Error("Model response did not contain valid JSON");
}

function isObject(val: unknown): val is Record<string, unknown> {
  return typeof val === "object" && val !== null && !Array.isArray(val);
}

/** Strips <think>, <thought>, <reasoning> blocks generated by reasoning/CoT models. */
function stripReasoningTags(text: string): string {
  let result = text;
  result = result.replace(/<think[\s\S]*?<\/think>/gi, "");
  result = result.replace(/<thought[\s\S]*?<\/thought>/gi, "");
  result = result.replace(/<reasoning[\s\S]*?<\/reasoning>/gi, "");
  result = result.replace(/<thought_process[\s\S]*?<\/thought_process>/gi, "");
  // If an unclosed <think> tag was emitted (e.g. truncated), strip up to the tag or everything inside
  if (/<\/?(?:think|thought|reasoning|thought_process)/i.test(result)) {
    result = result.replace(/<(?:think|thought|reasoning|thought_process)[^>]*>[\s\S]*$/i, "");
  }
  return result;
}

/** Extracts all code block contents from markdown ```...``` fences. */
function extractFencedBlocks(text: string): string[] {
  const blocks: string[] = [];
  const regex = /```(?:json)?\s*([\s\S]*?)```/gi;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(text)) !== null) {
    if (match[1]?.trim()) {
      blocks.push(match[1].trim());
    }
  }
  return blocks;
}

/** Finds potential JSON candidate substrings by scanning for matching braces and unclosed tails. */
function findJsonCandidates(text: string): string[] {
  const candidates: string[] = [];
  const openIndices: number[] = [];

  for (let i = 0; i < text.length; i++) {
    if (text[i] === "{") {
      openIndices.push(i);
    }
  }

  // Scan from each "{" to its balanced "}"
  for (const start of openIndices) {
    let depth = 0;
    let inString = false;
    let quoteChar = '"';
    let escaped = false;
    let foundBalanced = false;

    for (let j = start; j < text.length; j++) {
      const ch = text[j];

      if (inString) {
        if (escaped) {
          escaped = false;
        } else if (ch === "\\") {
          escaped = true;
        } else if (ch === quoteChar) {
          inString = false;
        }
        continue;
      }

      if (ch === '"' || ch === "'") {
        inString = true;
        quoteChar = ch;
      } else if (ch === "{") {
        depth += 1;
      } else if (ch === "}") {
        depth -= 1;
        if (depth === 0) {
          candidates.push(text.slice(start, j + 1));
          foundBalanced = true;
          break;
        }
      }
    }

    // If no balanced "}" was found (e.g. truncated output), take the slice to the end
    if (!foundBalanced && depth > 0) {
      candidates.push(text.slice(start));
    }
  }

  // Sort candidates by length descending so larger, more complete JSON objects are tried first
  candidates.sort((a, b) => b.length - a.length);
  return candidates;
}

/** Tries to parse directly, then with progressive JSON repairs. */
function tryParse(raw: string): unknown | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;

  // 1. Direct standard parse
  try {
    return JSON.parse(trimmed);
  } catch {
    // Continue to repair
  }

  // 2. Repair common LLM syntax flaws
  try {
    const repaired = repairJson(trimmed);
    return JSON.parse(repaired);
  } catch {
    return null;
  }
}

/**
 * Repairs common JSON syntax issues produced by LLMs:
 * - Strips comments (// and /* * /)
 * - Normalizes Python literals (True, False, None)
 * - Fixes single quoted keys/strings
 * - Fixes unescaped newlines/tabs inside strings
 * - Removes trailing commas in objects and arrays
 * - Auto-completes unclosed braces and brackets
 */
export function repairJson(input: string): string {
  let text = input.trim();

  // Strip single-line and multi-line comments outside strings
  text = stripComments(text);

  // Normalize Python literals outside strings
  text = normalizeLiterals(text);

  // Fix single quotes to double quotes
  text = fixSingleQuotes(text);

  // Fix unescaped control characters and newlines inside string literals
  text = fixUnescapedStringLiterals(text);

  // Remove trailing commas before } or ]
  text = text.replace(/,(\s*[}\]])/g, "$1");

  // Auto-complete unclosed quotes and brackets
  text = autoCompleteBrackets(text);

  // Final trailing comma cleanup in case autocomplete created any
  text = text.replace(/,(\s*[}\]])/g, "$1");

  return text;
}

function stripComments(text: string): string {
  let out = "";
  let inString = false;
  let quoteChar = '"';
  let escaped = false;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    const next = text[i + 1];

    if (inString) {
      out += ch;
      if (escaped) {
        escaped = false;
      } else if (ch === "\\") {
        escaped = true;
      } else if (ch === quoteChar) {
        inString = false;
      }
      continue;
    }

    if (ch === '"' || ch === "'") {
      inString = true;
      quoteChar = ch;
      out += ch;
    } else if (ch === "/" && next === "/") {
      // Skip until newline
      const nextNewline = text.indexOf("\n", i);
      if (nextNewline === -1) break;
      i = nextNewline - 1;
    } else if (ch === "/" && next === "*") {
      // Skip until */
      const nextEnd = text.indexOf("*/", i + 2);
      if (nextEnd === -1) break;
      i = nextEnd + 1;
    } else {
      out += ch;
    }
  }

  return out;
}

function normalizeLiterals(text: string): string {
  let out = "";
  let inString = false;
  let quoteChar = '"';
  let escaped = false;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];

    if (inString) {
      out += ch;
      if (escaped) {
        escaped = false;
      } else if (ch === "\\") {
        escaped = true;
      } else if (ch === quoteChar) {
        inString = false;
      }
      continue;
    }

    if (ch === '"' || ch === "'") {
      inString = true;
      quoteChar = ch;
      out += ch;
      continue;
    }

    // Check for True / False / None words
    const slice = text.slice(i);
    if (/^True\b/.test(slice)) {
      out += "true";
      i += 3;
    } else if (/^False\b/.test(slice)) {
      out += "false";
      i += 4;
    } else if (/^None\b/.test(slice)) {
      out += "null";
      i += 3;
    } else {
      out += ch;
    }
  }

  return out;
}

function fixSingleQuotes(text: string): string {
  // If the text already has valid double-quoted structure, don't blindly mangle
  if (text.includes('"') && !text.includes("'")) return text;

  let out = "";
  let inDouble = false;
  let inSingle = false;
  let escaped = false;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];

    if (inDouble) {
      out += ch;
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inDouble = false;
      continue;
    }

    if (inSingle) {
      if (escaped) {
        out += ch;
        escaped = false;
      } else if (ch === "\\") {
        out += ch;
        escaped = true;
      } else if (ch === "'") {
        out += '"';
        inSingle = false;
      } else if (ch === '"') {
        out += '\\"';
      } else {
        out += ch;
      }
      continue;
    }

    if (ch === '"') {
      inDouble = true;
      out += ch;
    } else if (ch === "'") {
      inSingle = true;
      out += '"';
    } else {
      out += ch;
    }
  }

  return out;
}

function fixUnescapedStringLiterals(text: string): string {
  let out = "";
  let inString = false;
  let escaped = false;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];

    if (!inString) {
      out += ch;
      if (ch === '"') {
        inString = true;
        escaped = false;
      }
      continue;
    }

    // Inside double-quoted string
    if (escaped) {
      out += ch;
      escaped = false;
      continue;
    }

    if (ch === "\\") {
      out += ch;
      escaped = true;
      continue;
    }

    if (ch === '"') {
      inString = false;
      out += ch;
      continue;
    }

    // Replace unescaped control characters
    if (ch === "\n") {
      out += "\\n";
    } else if (ch === "\r") {
      out += "\\r";
    } else if (ch === "\t") {
      out += "\\t";
    } else if (ch.charCodeAt(0) < 0x20) {
      out += "\\u" + ch.charCodeAt(0).toString(16).padStart(4, "0");
    } else {
      out += ch;
    }
  }

  return out;
}

function autoCompleteBrackets(text: string): string {
  let inString = false;
  let escaped = false;
  const stack: string[] = [];

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (ch === "\\") {
        escaped = true;
      } else if (ch === '"') {
        inString = false;
      }
      continue;
    }

    if (ch === '"') {
      inString = true;
      continue;
    }

    if (ch === "{") {
      stack.push("}");
    } else if (ch === "[") {
      stack.push("]");
    } else if (ch === "}" || ch === "]") {
      if (stack.length > 0 && stack[stack.length - 1] === ch) {
        stack.pop();
      }
    }
  }

  let result = text;
  if (inString) {
    result += '"';
  }

  while (stack.length > 0) {
    result += stack.pop();
  }

  return result;
}
